# 1. Define global ARG (must be before the first FROM)
ARG BASEIMAGE=python:3.11-slim

# --- Use the official uv image to copy the binary ---
FROM ghcr.io/astral-sh/uv:latest AS uv_bin

# --- Pull official base image ---
FROM ${BASEIMAGE}

# 2. Re-declare the ARG here so this stage can see it (Docker scope rule)
ARG BASEIMAGE

# Install uv by copying it from the official image
COPY --from=uv_bin /uv /uvx /bin/

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/workspace/.venv/bin:$PATH"

# ------ Set up workspace dependencies -------- #
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Set Workspace
WORKDIR /workspace

# --- Install Python dependencies using uv --- #
RUN uv venv /workspace/.venv
RUN uv pip install \
    ipython==8.20.0 \
    numpy==1.26.4 \
    fastapi==0.110.0 \
    uvicorn==0.28.0 \
    pandas==2.1.4 \
    mlflow==3.10.1 \
    catboost==1.2 \
    python-multipart==0.0.22

# --- Copy source code --- #
COPY ./src ./src

# --- Start Command --- #
# Default to uvicorn, but docker-compose 'command' will override this
CMD ["uv", "run", "uvicorn", "--app-dir", "src", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8081"]