# --- pull official base image --- #
ARG BASEIMAGE=python:3.11-slim

FROM $BASEIMAGE as base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# ------ Set up workspace -------- #
RUN true && apt-get update
RUN apt update
RUN apt-get install -y curl
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y gcc


## --- Install python --- #
RUN true \
    && python -m pip install --upgrade pip \
    && python -m pip install --upgrade pip setuptools \
    && python -m pip install \
      ipython==8.20.0 \
      numpy==1.26.4 \
      fastapi==0.110.0 \
      uvicorn==0.28.0

# --- pull official base image --- #
RUN mkdir /workspace

# --- Make temp file for source code --- #
COPY ./src /workspace/src


# --- Set Workspace --- #
WORKDIR "/workspace"

# --- Start Jupyter Notebook --- #
CMD ["uvicorn", "--app-dir", "src", "main_app:app", "--reload", "--host", "0.0.0.0", "--port", "8081"]